administrator:
  description: "Rights on all the website and features."
  sites:
    resources: all
    actions: all
  layouts:
    resources: all
    actions: all
  workflow:
    resources: all
    actions: all
  mediafolders:
    resources: all
    actions: all
  pages:
    resources: all
    actions: all
  contents:
    resources: all
    actions: all
  bundles:
    resources: all
    actions: all
  users:
    resources: all
    actions: all
  groups:
    resources: all
    actions: all

validator:
  description: "Rights on creation, edition and publication of pages. Can only view the rest of the website."
  sites:
   resources: all
   actions: [view]
  layouts:
    resources: all
    actions: [view]
  workflow:
    resources: all
    actions: all
  mediafolders:
    resources: all
    actions: all
  pages:
    resources: all
    actions: [view, create, edit, publish]
  contents:
    resources: all
    actions: all
  bundles:
    resources: all
    actions: all
  users:
    resources: all
    actions: [view]
  groups:
    resources: all
    actions: [view]

contributor:
  description: "Rights on creation, edition of pages. Can only view the rest of the website."
  sites:
   resources: all
   actions: [view]
  layouts:
    resources: all
    actions: [view]
  workflow:
    resources: all
    actions: all
  mediafolders:
    resources: all
    actions: all
  pages:
    resources: all
    actions: [view, create, edit]
  contents:
    resources: all
    actions: all
  bundles:
    resources: all
    actions: all
  users:
    resources: all
    actions: [view]
  groups:
    resources: all
    actions: [view]