keywords:
  name: 'keywords'
  content:
    default: 'cms, content manager'
    layout: 
      Article: $ContentSet[0]->$Article/Article[0]->$keywords
description:
  name: 'description'
  content:
    default: "backbee demo website"
    layout: 
      Article: $ContentSet[0]->$Article/Article[0]->$abstract    
  lang: 'en'
robots:
  name: 'robots'
  content:
    default: ''
    select: ['', 'noindex', 'nofollow', 'noindex, nofollow']
title:
  name: 'title'
  content:
    default: ''
