facebook:
    link: "https://www.facebook.com/backbeeCMS"
    fa_icon: "facebook"
    title: "Facebook"

twitter:
    link: "https://twitter.com/lpdigitalsystem"
    widget_id: "606481211662475264"
    fa_icon: "twitter"
    title: "Twitter"

github:
    link: "https://github.com/backbee/backbee-standard"
    fa_icon: "github"
    title: "Github"
